---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - intelligentimageupdater.imagix.myk8soperator.com
  resources:
  - intelligentimageupdaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intelligentimageupdater.imagix.myk8soperator.com
  resources:
  - intelligentimageupdaters/finalizers
  verbs:
  - update
- apiGroups:
  - intelligentimageupdater.imagix.myk8soperator.com
  resources:
  - intelligentimageupdaters/status
  verbs:
  - get
  - patch
  - update
