apiVersion: intelligentimageupdater.imagix.myk8soperator.com/v1
kind: IntelligentImageUpdater
metadata:
  labels:
    app.kubernetes.io/name: imagix
    app.kubernetes.io/managed-by: kustomize
  name: intelligentimageupdater-sample
spec:
  # TODO(user): Add fields here
